/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import Database.Login;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import sedra.Colors;
import sedra.SedraUI;
import static sedra.SedraUI.accountPanel;
import static sedra.SedraUI.addCustomerPanel;
import static sedra.SedraUI.height;
import static sedra.SedraUI.homePanel;
import static sedra.SedraUI.receiptPanel;
import static sedra.SedraUI.width;

/**
 *
 * @author mohammed
 */
public class LoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginPanel
     */
    public LoginPanel() {
        initComponents();
        setBounds(0, 0, 3 * width / 4, 3 * height);
        loginPane.setBounds(0, 0, 3 * width / 4,  height);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPane = new javax.swing.JPanel();
        loginUserName = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        loginPassword = new javax.swing.JPasswordField();

        setLayout(null);

        loginPane.setBackground(Colors.PANELS_COLOR);

        loginUserName.setBackground(Colors.PANELS_COLOR);
        loginUserName.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        loginUserName.setForeground(Colors.LABELS_COLOR);
        loginUserName.setText("Email");
        loginUserName.setAlignmentX(5.0F);
        loginUserName.setBorder(null);
        loginUserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginUserNameFocusGained(evt);
            }
        });
        loginUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginUserNameActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(45, 33, 89));
        jSeparator1.setForeground(new java.awt.Color(45, 33, 89));

        jSeparator2.setBackground(new java.awt.Color(45, 33, 89));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Password_50.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Name_50.png"))); // NOI18N

        loginButton.setBackground(Colors.LABELS_COLOR);
        loginButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        loginButton.setForeground(new java.awt.Color(204, 204, 204));
        loginButton.setText("Login");
        loginButton.setBorder(null);
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(45, 33, 89));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel3.setForeground(Colors.LABELS_COLOR);
        jLabel3.setText("Login");

        loginPassword.setBackground(Colors.PANELS_COLOR);
        loginPassword.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        loginPassword.setForeground(Colors.LABELS_COLOR);
        loginPassword.setText("password");
        loginPassword.setBorder(null);
        loginPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginPasswordFocusGained(evt);
            }
        });

        javax.swing.GroupLayout loginPaneLayout = new javax.swing.GroupLayout(loginPane);
        loginPane.setLayout(loginPaneLayout);
        loginPaneLayout.setHorizontalGroup(
            loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPaneLayout.createSequentialGroup()
                .addGroup(loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPaneLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginPaneLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(loginPaneLayout.createSequentialGroup()
                                .addGroup(loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(loginUserName)
                                    .addComponent(jSeparator2)
                                    .addComponent(jSeparator1)
                                    .addComponent(loginPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE))))))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        loginPaneLayout.setVerticalGroup(
            loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPaneLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(loginUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(loginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        add(loginPane);
        loginPane.setBounds(0, 0, 760, 580);
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        if (SedraUI.loginLabel.getText().equalsIgnoreCase("login")) {
            Boolean success = false;
            Login login = new Login();
            login.setUsername(loginUserName.getText().toLowerCase().toString());
            login.setPassword(new String(loginPassword.getPassword()));
            try {
                success = login.execute();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Unable to login " + ex.getMessage());
            }
            if (success) {
                Colors.setColor(SedraUI.homePane);
                Colors.resetColor(SedraUI.salesPane);
                Colors.resetColor(SedraUI.accountPane);
                Colors.resetColor(SedraUI.customerPane1);
                Colors.resetColor(SedraUI.loginPane);
                Colors.resetColor(SedraUI.updatePane);
                SedraUI.accountPanel.setVisible(false);
                SedraUI.loginPanel.setVisible(false);
                SedraUI.loginLabel.setText("Sign up");

                SedraUI.homePanel.setVisible(true);
                homePanel.setEnabled(true);
                receiptPanel.setEnabled(true);
                addCustomerPanel.setEnabled(true);
                SedraUI.salesPane.setEnabled(true);
                accountPanel.setEnabled(true);

            } else {
                SedraUI.loginPanel.setVisible(true);
                loginPane.setVisible(true);

                JOptionPane.showMessageDialog(this, "Email or password is incorrect", "Unable to connect", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            SedraUI.loginLabel.setText("Login");

            homePanel.setEnabled(false);
            receiptPanel.setEnabled(false);
            addCustomerPanel.setEnabled(false);
            accountPanel.setEnabled(false);
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void loginUserNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginUserNameFocusGained
        // TODO add your handling code here:
        loginUserName.setText("");
    }//GEN-LAST:event_loginUserNameFocusGained

    private void loginPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginPasswordFocusGained
        // TODO add your handling code here:
        loginPassword.setText("");

    }//GEN-LAST:event_loginPasswordFocusGained

    private void loginUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginUserNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginPane;
    private javax.swing.JPasswordField loginPassword;
    private javax.swing.JTextField loginUserName;
    // End of variables declaration//GEN-END:variables
}
