/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import Database.Connect;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sedra.Colors;

/**
 *
 * @author mohammed
 */
public class NewJFrame2 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame2
     */
    DefaultTableModel dtm;
    private String recID;

    public NewJFrame2(String name, float total, String recID, String customerType) throws SQLException {
        initComponents();
        Connection conn = DriverManager.getConnection(Connect.URL, Connect.HOST_NAME, Connect.PASSWORD);
        Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        Statement stmt2 = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        ResultSet resultSet = stmt.executeQuery("SELECT itemID,Size,salesQuantity FROM Sales where recID='" + recID + "'");
        ResultSet resultSet2 = null;
        this.recID = recID;
        String s0;
        String s1;
        String s2;
        naming.setText(name);
        this.total.setText("Total= " + total);

        dtm = (DefaultTableModel) tableForSpecificData.getModel();
        dtm.setRowCount(0);
        while (resultSet.next()) {
            s0 = resultSet.getString(1);
            s1 = resultSet.getString(2);
            s2 = resultSet.getString(3);
            if (customerType.equalsIgnoreCase("Doctor")) {
                resultSet2 = stmt2.executeQuery("SELECT itemDocPrice FROM Store where itemID='" + s0 + "' AND itemSize='" + s1 + "'");

            } else if (customerType.equalsIgnoreCase("Customer")) {
                resultSet2 = stmt2.executeQuery("SELECT itemCustomerPrice FROM Store where itemID='" + s0 + "' AND itemSize='" + s1 + "'");

            }
            resultSet2.next();
            String s3 = resultSet2.getString(1);

            Object o[] = {s0, s1, s2, s3};

            dtm.addRow(o);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        tableForSpecificData = new javax.swing.JTable();
        total = new javax.swing.JLabel();
        naming = new javax.swing.JLabel();
        submit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableForSpecificData.setBackground(new java.awt.Color(255, 255, 255));
        tableForSpecificData.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tableForSpecificData.setForeground(Colors.LABELS_COLOR);
        tableForSpecificData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Size", "Quantity", "price/item", "pay"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tableForSpecificData);
        if (tableForSpecificData.getColumnModel().getColumnCount() > 0) {
            tableForSpecificData.getColumnModel().getColumn(3).setResizable(false);
            tableForSpecificData.getColumnModel().getColumn(4).setResizable(false);
        }

        total.setText("Total =");

        naming.setText("CustomerName");
        naming.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                namingMousePressed(evt);
            }
        });

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 883, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(naming)
                                .addGap(0, 778, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submit)
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(naming)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        Connection c;
        Statement s = null;
        ResultSet resultSet;
        try {
            c = DriverManager.getConnection(Connect.URL, Connect.HOST_NAME, Connect.PASSWORD);
            s = c.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);

        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (int i = 0; i < dtm.getRowCount(); i++) {
            if (dtm.getValueAt(i, 4).toString().trim().length() > 0) {
                try {
                    s.executeUpdate("UPDATE Sales set salesPaid=" + Float.parseFloat((String) dtm.getValueAt(i, 4)) + " WHERE "
                            + "itemID='" + dtm.getValueAt(i, 0) + "' AND Size='" + dtm.getValueAt(i, 1) + "' AND recID=" + recID);
                } catch (SQLException ex) {
                    Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        JOptionPane.showMessageDialog(this, "Done");
        this.dispose();
    }//GEN-LAST:event_submitActionPerformed

    private void namingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_namingMousePressed
        try {
            // TODO add your handling code here:

            tableForSpecificData.print();
        } catch (PrinterException ex) {
            Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_namingMousePressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel naming;
    private javax.swing.JButton submit;
    public static javax.swing.JTable tableForSpecificData;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
