/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import Database.Items;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import sedra.Colors;
import static sedra.SedraUI.height;
import static sedra.SedraUI.width;

/**
 *
 * @author mohammed
 */
public class NewPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginPanel
     */
    public NewPanel() {
        initComponents();
        setBounds(0, 0, 3 * width / 4, height);
        loginPane.setBounds(0, 0, 3 * width / 4, height);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPane = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Update = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        updateItemNameField = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        updateItemCustomerPrice = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        updateItemDoctorPrice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        newItemQuantity = new javax.swing.JComboBox<>();
        newItemSize = new javax.swing.JComboBox<>();

        setLayout(null);

        loginPane.setBackground(Colors.PANELS_COLOR);
        loginPane.setForeground(new java.awt.Color(204, 204, 204));

        jSeparator1.setBackground(new java.awt.Color(45, 33, 89));
        jSeparator1.setForeground(new java.awt.Color(45, 33, 89));

        jSeparator2.setBackground(new java.awt.Color(45, 33, 89));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Password_50.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Name_50.png"))); // NOI18N

        Update.setBackground(Colors.SIDE_COLOR);
        Update.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Update.setForeground(new java.awt.Color(204, 204, 204));
        Update.setText("Add");
        Update.setBorder(null);
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(45, 33, 89));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel3.setForeground(Colors.LABELS_COLOR);
        jLabel3.setText("Add Code");

        updateItemNameField.setBackground(Colors.FIELDS_COLOR);
        updateItemNameField.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        updateItemNameField.setForeground(Colors.LABELS_COLOR);
        updateItemNameField.setText("Code");
        updateItemNameField.setAlignmentX(5.0F);
        updateItemNameField.setBorder(null);
        updateItemNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                updateItemNameFieldFocusGained(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(45, 33, 89));

        updateItemCustomerPrice.setBackground(Colors.FIELDS_COLOR);
        updateItemCustomerPrice.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        updateItemCustomerPrice.setForeground(Colors.LABELS_COLOR);
        updateItemCustomerPrice.setText("CustomerPrice");
        updateItemCustomerPrice.setAlignmentX(5.0F);
        updateItemCustomerPrice.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));
        updateItemCustomerPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                updateItemCustomerPriceFocusGained(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(45, 33, 89));
        jSeparator4.setForeground(new java.awt.Color(45, 33, 89));

        updateItemDoctorPrice.setBackground(Colors.FIELDS_COLOR);
        updateItemDoctorPrice.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        updateItemDoctorPrice.setForeground(Colors.LABELS_COLOR);
        updateItemDoctorPrice.setText("Doctor Price");
        updateItemDoctorPrice.setAlignmentX(5.0F);
        updateItemDoctorPrice.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));
        updateItemDoctorPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                updateItemDoctorPriceFocusGained(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Price_50.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Price_50.png"))); // NOI18N

        newItemQuantity.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        newItemQuantity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quantity", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99" }));

        newItemSize.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        newItemSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Size", "XS", "S", "M", "L", "XL", "XXL", "XXXL", "XXXXL", "XXXXXL", "XXXXXXL" }));

        javax.swing.GroupLayout loginPaneLayout = new javax.swing.GroupLayout(loginPane);
        loginPane.setLayout(loginPaneLayout);
        loginPaneLayout.setHorizontalGroup(
            loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPaneLayout.createSequentialGroup()
                .addGroup(loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(loginPaneLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(updateItemDoctorPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPaneLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addGroup(loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator3)
                                .addComponent(jSeparator4)
                                .addComponent(updateItemCustomerPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                                .addComponent(Update, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, loginPaneLayout.createSequentialGroup()
                            .addGap(145, 145, 145)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(loginPaneLayout.createSequentialGroup()
                            .addGap(120, 120, 120)
                            .addGroup(loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(jSeparator1))
                                .addGroup(loginPaneLayout.createSequentialGroup()
                                    .addGroup(loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(updateItemNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(loginPaneLayout.createSequentialGroup()
                                            .addComponent(newItemQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(newItemSize, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        loginPaneLayout.setVerticalGroup(
            loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPaneLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateItemNameField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(loginPaneLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addGroup(loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(newItemQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                            .addComponent(newItemSize)))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateItemDoctorPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(loginPaneLayout.createSequentialGroup()
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(updateItemCustomerPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        add(loginPane);
        loginPane.setBounds(0, 0, 766, 580);
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:

        try {
            Items items = new Items();
            items.setName(updateItemNameField.getText());
            items.setQuantity(Integer.parseInt(newItemQuantity.getSelectedItem().toString()));
            items.setCusPrice(Float.parseFloat(updateItemCustomerPrice.getText().toLowerCase()));
            items.setDocPrice(Float.parseFloat(updateItemDoctorPrice.getText().toLowerCase()));
            items.setSize(newItemSize.getSelectedItem().toString().toLowerCase());
            items.addNew();
            newItemQuantity.setSelectedIndex(0);
            newItemSize.setSelectedIndex(0);
            updateItemNameField.setText("Code");
            updateItemCustomerPrice.setText("CustomerPrice");
            updateItemDoctorPrice.setText("DocPrice");
        } catch (NumberFormatException numberFormatException) {
            JOptionPane.showMessageDialog(this, "Check Prices Values");
        }


    }//GEN-LAST:event_UpdateActionPerformed

    private void updateItemNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_updateItemNameFieldFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_updateItemNameFieldFocusGained

    private void updateItemCustomerPriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_updateItemCustomerPriceFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_updateItemCustomerPriceFocusGained

    private void updateItemDoctorPriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_updateItemDoctorPriceFocusGained
        // TODO add your handling code here:
       
    }//GEN-LAST:event_updateItemDoctorPriceFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel loginPane;
    private javax.swing.JComboBox<String> newItemQuantity;
    private javax.swing.JComboBox<String> newItemSize;
    private javax.swing.JTextField updateItemCustomerPrice;
    private javax.swing.JTextField updateItemDoctorPrice;
    private javax.swing.JTextField updateItemNameField;
    // End of variables declaration//GEN-END:variables
}
